# vars/default_example.yml
# modify for each deployment
---
user_name: gai
sys_packages: ['nginx', 'curl', 'wget', 'vim', 'git', 'tree', 'ufw', 'whois','python3-virtualenv','python3-pip','python3-dev','libpq-dev']
project_repo: https://github.com/gibeongideon/daruapp.git

app_name: daruproject
django_project_name: daruapp
app_dir: "/home/{{ user_name }}/{{ app_name }}"
django_secret_key: 2x4o=3b1n-n*_ls9bg@*$pcx3^pz)z7b@9o)=hz7^0%9&!wo0s
server_IP: 198.XXX.XXX.XX#
fixture_path: /home/gai/app-dir/daruapp/fixtures/data.json

django_superuser: gai
django_superuser_password: darius!@#$2021@casino.us!
domain_name: dwinnings.com
email: kipngeno.gibeon@gmail.com


#postgresql_db
database_name: dariusdb
database_password: dariusdbpasscode


