# Generated by Django 3.1.7 on 2021-05-24 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daru_wheel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CumulativeGain',
            new_name='Analytic',
        ),
    ]
