# Generated by Django 3.1.4 on 2021-02-18 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daru_wheel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='istake',
            old_name='real',
            new_name='bet_on_real_account',
        ),
    ]
