# Generated by Django 3.1.4 on 2021-02-24 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('daru_wheel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stake',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_wp_stakes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='selection',
            name='mrtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mrtypes', to='daru_wheel.markettype'),
        ),
        migrations.AddField(
            model_name='result',
            name='cumgain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gains', to='daru_wheel.cumulativegain'),
        ),
        migrations.AddField(
            model_name='result',
            name='market',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rmarkets', to='daru_wheel.wheelspin'),
        ),
        migrations.AddField(
            model_name='outcome',
            name='market',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketoutcomes', to='daru_wheel.wheelspin'),
        ),
        migrations.AddField(
            model_name='istake',
            name='marketselection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imarketselections', to='daru_wheel.selection'),
        ),
        migrations.AddField(
            model_name='istake',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_wp_istakes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ioutcome',
            name='cashstore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashstores', to='daru_wheel.cashstore'),
        ),
        migrations.AddField(
            model_name='ioutcome',
            name='stake',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='istakes', to='daru_wheel.istake'),
        ),
    ]
