# Generated by Django 3.1.4 on 2021-02-27 10:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('daru_wheel', '0002_auto_20210227_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='closed_at',
        ),
        migrations.RemoveField(
            model_name='market',
            name='open_at',
        ),
        migrations.RemoveField(
            model_name='market',
            name='results_at',
        ),
        migrations.AddField(
            model_name='wheelspin',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='wheelspin',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wheelspin',
            name='open_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='wheelspin',
            name='results_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='markettype',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
