# Generated by Django 3.1.4 on 2021-02-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daru_wheel', '0002_auto_20210218_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='daruwheelsetting',
            name='min_bet',
            field=models.DecimalField(blank=True, decimal_places=2, default=4.9, max_digits=5, null=True),
        ),
    ]
