# Generated by Django 3.1.4 on 2021-02-23 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daru_wheel', '0002_auto_20210222_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('result', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='istake',
            name='outcome_received',
            field=models.BooleanField(default=False),
        ),
    ]
