# Generated by Django 3.1.4 on 2021-02-19 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daru_wheel', '0003_daruwheelsetting_min_bet'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('give_away', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='give_away')),
                ('to_keep', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='to_keep')),
            ],
        ),
        migrations.AlterField(
            model_name='daruwheelsetting',
            name='min_bet',
            field=models.DecimalField(blank=True, decimal_places=2, default=45.9, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='ioutcome',
            name='cashstore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashstores', to='daru_wheel.cashstore'),
        ),
    ]
