
name: Daruapp CI/CD

on:
  push:
    branches: [ prod ]
  # pull_request:
  #   branches: [ prod ]
    # paths-ignore:
    # - "migrations/**"


jobs:
  build:

    runs-on: ubuntu-latest
    name: build

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r requirements.txt


    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Collectstatic, makemigrations & migrate
      run: |

        # cd ~/daruapp/actions-runner/deploy/daruapp/daruapp        
        python manage.py collectstatic
        python manage.py makemigrations users
        python manage.py makemigrations account
        python manage.py makemigrations daru_wheel
        python manage.py makemigrations dashboard
        python manage.py makemigrations core
        python manage.py makemigrations

        python manage.py migrate

    - name: Run Tests
      run: |
        python manage.py test account users daru_wheel



  # deploy:
  #   runs-on: self-hosted
  #   needs: build
  #   name: deploy to Cloud with actions runner


  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python 3.8
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.8

  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install -r requirements.txt

  #   - name: Collect static
  #     run: python manage.py collectstatic 

  #   - name: Apply migrations
  #     run: python manage.py migrate

    # - name: Run Tests
    #   run: |
    #     python manage.py test account

  deploy:
    runs-on: ubuntu-latest
    needs: build
    name: deploy to Cloud through ssh


    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8


    - name: Executing remote  command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
         USERNAME: ${{ secrets.USERNAME }}
         PORT: ${{ secrets.PORT }}
         KEY: ${{ secrets.SSHPKEY }}
         script: |
              cd ~/darius/daruapp && git pull https://github.com/gibeongideon/daruapp.git
              #cd ~/darius/daruapp && git fetch origin prod  && git reset --hard origin/prod
              cd ~/darius/
              sourcess venv/bin/activate
              python -m pip install --upgrade pip
              cd ~/darius/daruapp
              pip install -r requirements.txt
              python manage.py collectstatic
              python manage.py makemigrations
              python manage.py migrate
              

    # - name: Run Tests
    #   run: |
    #     python manage.py test account
   
