
name: daruapp CI/CD

on:
  push:
    branches: [ prod ]
  # pull_request:
  #   branches: [ prod ]
    # paths-ignore:
    # - "migrations/**"


jobs:
  build:

    runs-on: ubuntu-latest
    name: build

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r requirements.txt


    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Collectstatic, makemigrations & migrate
      run: |

        # cd ~/daruapp/actions-runner/deploy/daruapp/daruapp        
        python manage.py collectstatic
        python manage.py makemigrations users
        python manage.py makemigrations account
        python manage.py makemigrations daru_wheel
        python manage.py makemigrations dashboard
        python manage.py makemigrations core
        python manage.py makemigrations

        python manage.py migrate

    - name: Run Tests
      run: |
        python manage.py test account users daru_wheel



  deploy:
    runs-on: self-hosted
    needs: build
    name: deploy


    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        pwd
        cd ~/daruapp/actions-runner/deploy/daruapp/daruapp
        
        python -m pip install --upgrade pip    
        python -m pip install tree
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Create ENV VAR
      run: |  
        touch ~/daruapp/.env
        cp ~/daruapp/.env  ~/daruapp/actions-runner/deploy/daruapp/daruapp


    - name: Create Migrations Backup Directories
      run: |  
        mkdir -p ~/daruapp/daruapp/migrations/account/migrations
        mkdir -p ~/daruapp/daruapp/migrations/daru_wheel/migrations
        mkdir -p ~/daruapp/daruapp/migrations/dashboard/migrations
        mkdir -p ~/daruapp/daruapp/migrations/users/migrations
        mkdir -p ~/daruapp/daruapp/migrations/mpesa_api/core/migrations
        mkdir -p ~/daruapp/daruapp/migrations/paypal/standard/ipn/migrations
        mkdir -p ~/daruapp/daruapp/migrations/paypal/pro/migrations

        cd ~/daruapp/daruapp/migrations
        tree


    - name: RSYNC Backup Migrations To Workin Directory
      run: |
        rsync -a --delete ~/daruapp/daruapp/migrations/account/migrations ~/daruapp/actions-runner/deploy/daruapp/daruapp/account
        rsync -a --delete ~/daruapp/daruapp/migrations/daru_wheel/migrations ~/daruapp/actions-runner/deploy/daruapp/daruapp/daru_wheel
        rsync -a --delete ~/daruapp/daruapp/migrations/dashboard/migrations ~/daruapp/actions-runner/deploy/daruapp/daruapp/dashboard
        rsync -a --delete ~/daruapp/daruapp/migrations/users/migrations ~/daruapp/actions-runner/deploy/daruapp/daruapp/users
        rsync -a --delete ~/daruapp/daruapp/migrations/mpesa_api/core/migrations ~/daruapp/actions-runner/deploy/daruapp/daruapp/mpesa_api/core
        rsync -a --delete ~/daruapp/daruapp/migrations/paypal/standard/ipn/migrations ~/daruapp/actions-runner/deploy/daruapp/daruapp/paypal/standard/ipn
        rsync -a --delete ~/daruapp/daruapp/migrations/paypal/pro/migrations ~/daruapp/actions-runner/deploy/daruapp/daruapp/paypal/pro

        
    - name: COLLECTSTATIC
      run: |
        cd ~/daruapp/actions-runner/deploy/daruapp/daruapp                
        python manage.py collectstatic

    - name: MAKEMIGRATIONS
      run: |
        cd ~/daruapp/actions-runner/deploy/daruapp/daruapp  

        python manage.py makemigrations users
        python manage.py makemigrations account
        python manage.py makemigrations daru_wheel
        python manage.py makemigrations dashboard
        python manage.py makemigrations core
        python manage.py makemigrations ipn
        python manage.py makemigrations pro

    ## account
    - name: MIGRATE-account
      run: |
        cd ~/daruapp/actions-runner/deploy/daruapp/daruapp        
        python manage.py migrate account

    - name: Rsync Workin Directory to Backup Migrations-account
      run: |
        rsync -a --delete ~/daruapp/actions-runner/deploy/daruapp/daruapp/account/migrations ~/daruapp/daruapp/migrations/account
        cd ~/daruapp/daruapp/migrations/account
        tree

    ## daru_wheel
    - name: MIGRATE-daru_wheel
      run: |
        cd ~/daruapp/actions-runner/deploy/daruapp/daruapp        
        python manage.py migrate daru_wheel

    - name: Rsync Workin Directory to Backup Migrations-daru_wheel
      run: |
        rsync -a --delete ~/daruapp/actions-runner/deploy/daruapp/daruapp/daru_wheel/migrations ~/daruapp/daruapp/migrations/daru_wheel
        cd ~/daruapp/daruapp/migrations/daru_wheel
        tree
    ## dashboard    
    - name: MIGRATE-dashboard
      run: |
        cd ~/daruapp/actions-runner/deploy/daruapp/daruapp        
        python manage.py migrate dashboard

    - name: Rsync Workin Directory to Backup Migrations-dashboard
      run: |
        rsync -a --delete ~/daruapp/actions-runner/deploy/daruapp/daruapp/dashboard/migrations ~/daruapp/daruapp/migrations/dashboard
        cd ~/daruapp/daruapp/migrations/dashboard
        tree

    ## users
    - name: MIGRATE-users
      run: |
        cd ~/daruapp/actions-runner/deploy/daruapp/daruapp        
        python manage.py migrate users

    - name: Rsync Workin Directory to Backup Migrations-users
      run: |
        rsync -a --delete ~/daruapp/actions-runner/deploy/daruapp/daruapp/users/migrations ~/daruapp/daruapp/migrations/users
        cd ~/daruapp/daruapp/migrations/users
        tree    

    ## core
    - name: MIGRATE-core
      run: |
        cd ~/daruapp/actions-runner/deploy/daruapp/daruapp        
        python manage.py migrate core

    - name: Rsync Workin Directory to Backup Migrations-core
      run: |
        rsync -a --delete ~/daruapp/actions-runner/deploy/daruapp/daruapp/mpesa_api/core/migrations ~/daruapp/daruapp/migrations/mpesa_api/core
        cd ~/daruapp/daruapp/migrations/core
        tree   

    ## ipn
    - name: MIGRATE-ipn
      run: |
        cd ~/daruapp/actions-runner/deploy/daruapp/daruapp        
        python manage.py migrate ipn

    - name: Rsync Workin Directory to Backup Migrations-ipn
      run: |
        rsync -a --delete ~/daruapp/actions-runner/deploy/daruapp/daruapp/paypal/standard/ipn/migrations ~/daruapp/daruapp/migrations/paypal/standard/ipn 
        cd ~/daruapp/daruapp/migrations/ipn
        tree 

    ## pro
    - name: MIGRATE-pro
      run: |
        cd ~/daruapp/actions-runner/deploy/daruapp/daruapp        
        python manage.py migrate pro

    - name: Rsync Workin Directory to Backup Migrations-pro
      run: |
        rsync -a --delete ~/daruapp/actions-runner/deploy/daruapp/daruapp/paypal/pro/migrations ~/daruapp/daruapp/migrations/paypal/pro 
        cd ~/daruapp/daruapp/migrations/pro
        tree 

    - name: Backup Migrations_Updated
      run: |
        cd ~/daruapp/daruapp/migrations
        tree


    - name: Test Redis
      run: |
        redis-cli ping


    # - name: Run Tests
    #   run: |
    #     python manage.py test


    # - name: Reload
    #   run: |
    #     sudo shutdown -r now
