
name: Daruapp CI/CD

on:
  push:
    branches: [ prod ]
  # pull_request:
  #   branches: [ prod ]
    # paths-ignore:
    # - "migrations/**"


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    # - name: Install Env dependencies
    #   run: |
    #     sudo -H pip3 install --upgrade pip
    #     sudo -H pip3 install virtualenv


    # - name: Create and start virtual environment
    #   run: |
    #     mkdir ~/myprojectdir
    #     cd ~/myprojectdir
    #     virtualenv myprojectenv
    #     source myprojectenv/bin/activate

        
    - name: Install dependencies
      run: |
        #python -m pip install --upgrade pip
        pip install flake8 #pytest
        #if [ -f requirements.txt ]; then pip install -r requirements.txt; fi


    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # - name: Test with pytest
    #   run: |
    #     pytest
    



  deploy:
    runs-on: self-hosted
    needs: build
    name: deploy to Cloud with actions runner


    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt

    # - name: Collect static
    #   run: python manage.py collectstatic 

    # - name: Apply migrations
    #   run: python manage.py migrate

    - name: Fix migrations Issues
      run: |
        # python -m pip install --upgrade pip
        pwd 
        python -m pip install tree
        mkdir -p ~/daruapp/daruapp/migrations 
        # cd ~/daruapp/daruapp/migrations
        # tree 

        mkdir -p ~/daruapp/daruapp/migrations/account/migrations
        mkdir -p ~/daruapp/daruapp/migrations/daru_wheel/migrations
        mkdir -p ~/daruapp/daruapp/migrations/dashboard/migrations
        mkdir -p ~/daruapp/daruapp/migrations/users/migrations
        mkdir -p ~/daruapp/daruapp/migrations/mpesa_api/core/migrations

        cd ~/daruapp/daruapp/migrations
        tree

        rsync -a --delete ~/daruapp/daruapp/migrations/account/migrations ~/daruapp/actions-runner/deploy/daruapp/daruapp/account
        rsync -a --delete ~/daruapp/daruapp/migrations/daru_wheel/migrations ~/daruapp/actions-runner/deploy/daruapp/daruapp/daru_wheel
        rsync -a --delete ~/daruapp/daruapp/migrations/dashboard/migrations ~/daruapp/actions-runner/deploy/daruapp/daruapp/dashboard
        rsync -a --delete ~/daruapp/daruapp/migrations/users/migrations ~/daruapp/actions-runner/deploy/daruapp/daruapp/users
        rsync -a --delete ~/daruapp/daruapp/migrations/mpesa_api/core/migrations ~/daruapp/actions-runner/deploy/daruapp/daruapp/mpesa_api/core

        cd ~/daruapp/actions-runner/deploy/daruapp/daruapp
        pip install -r requirements.txt
        python manage.py collectstatic
        python manage.py makemigrations users
        python manage.py makemigrations account
        python manage.py makemigrations daru_wheel
        python manage.py makemigrations dashboard
        python manage.py makemigrations

        python manage.py migrate

        rsync -a --delete ~/daruapp/actions-runner/deploy/daruapp/daruapp/account/migrations ~/daruapp/daruapp/migrations/account
        rsync -a --delete ~/daruapp/actions-runner/deploy/daruapp/daruapp/daru_wheel/migrations ~/daruapp/daruapp/migrations/daru_wheel
        rsync -a --delete ~/daruapp/actions-runner/deploy/daruapp/daruapp/dashboard/migrations ~/daruapp/daruapp/migrations/dashboard
        rsync -a --delete ~/daruapp/actions-runner/deploy/daruapp/daruapp/users/migrations ~/daruapp/daruapp/migrations/users
        rsync -a --delete ~/daruapp/actions-runner/deploy/daruapp/daruapp/mpesa_api/core/migrations ~/daruapp/daruapp/migrations/mpesa_api/core

        # cd ~/daruapp/daruapp/migrations
        # tree

    # - name: Run Tests
    #   run: |
    #     python manage.py test account

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   name: deploy to Cloud through ssh


  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python 3.8
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.8


  #   - name: Executing remote  command
  #     uses: appleboy/ssh-action@master
  #     with:
  #       host: ${{ secrets.HOST }}
  #        USERNAME: ${{ secrets.USERNAME }}
  #        PORT: ${{ secrets.PORT }}
  #        KEY: ${{ secrets.SSHPKEY }}
  #        script: |
  #             cd ~/darius/daruapp && git pull https://github.com/gibeongideon/daruapp.git
  #             #cd ~/darius/daruapp && git fetch origin prod  && git reset --hard origin/prod
  #             cd ~/darius/
  #             sourcess venv/bin/activate
  #             python -m pip install --upgrade pip
  #             cd ~/darius/daruapp
  #             pip install -r requirements.txt
  #             python manage.py collectstatic
  #             python manage.py makemigrations
  #             python manage.py migrate
              

    # - name: Run Tests
    #   run: |
    #     python manage.py test account
 
